default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: jmjny383
  pool: 5

production:
  <<: *default
  database: gps_production

development:
  <<: *default
  database: gps_development

test:
  <<: *default
  database: gps_test